In [4]:
#Determining a vector's span computationally using NumPy's linear algebra subpackage linalg.

#Importing numpy
import numpy as np

In [8]:
# Creates matrix v (right side of the augmented matrix).
v = np.array([4, 11])

# Creates matrix vw (left side of the augmented matrix).
x = np.array([[1, 2], [3, 5]])

print(v)
print(x)

[ 4 11]
[[1 2]
 [3 5]]


In [45]:
#Creating check_vector_span function using NumPy's linalg.solve function to check if vector v  
#is within the span of the other two vectors in x.

def check_vector_span(set_of_vectors, vectors_to_check):
    # Creates an empty vector of correct size
    vector_of_scalars = np.asarray([None]*set_of_vectors.shape[0])
    
    try:
        vector_of_scalars = np.linalg.solve(set_of_vectors, vectors_to_check)
        if not(vector_of_scalars is None):
            print("Vectors exist within span.\nScalar in s:", vector_of_scalars)
    # Handles the cases when the vector is NOT within the span
    except Exception as exception_type:
        if str(exception_type) == "Singular matrix":
            print("\nNo single solution\nVector is NOT within span")
        else:
            print("Unexpected error:", exception_type)
    return vector_of_scalars
        

In [46]:
print("Equation 1:\n Matrix 1:\n", x, "\nVectors:\n", v)
result = check_vector_span(x, v)

Equation 1:
 Matrix 1:
 [[1 2]
 [3 5]] 
Vectors:
 [ 4 11]
Vectors exist within span.
Scalar in s: [2. 1.]


In [48]:
v2 = np.array([6, 12])

x2 = np.array([[1, 2], [2, 4]])

print("\nMatrix x2:", x2, "\nVectors:", v2, sep="\n")
result = check_vector_span(x2, v2)


Matrix x2:
[[1 2]
 [2 4]]

Vectors:
[ 6 12]

No single solution
Vector is NOT within span
